name: Deploy to UMD Junkfood Server

on:
  push:
    branches:
      - master

jobs:
  deploy:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout Project Files
        uses: actions/checkout@v2
      - name: Install Julia
        uses: julia-actions/setup-julia@v1
        with:
          version: 1.5
      - name: Generate Static Site
        run: julia -e '
          using Pkg; Pkg.add(["NodeJS", "Franklin"]);
          using NodeJS; run(`$(npm_cmd()) install highlight.js`);
          using Franklin;
          Pkg.activate("."); Pkg.instantiate();
          optimize()'
      - name: Deploy to UMD CS Server over SSH
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          SSH_PRIVATE_KEY: ${{ secrets.SERVER_SSH_KEY }}
          REMOTE_HOST: ${{ secrets.REMOTE_HOST }}
          REMOTE_USER: ${{ secrets.REMOTE_USER }}
          SOURCE: "__site/"
          TARGET: ${{ secrets.REMOTE_TARGET }}
